//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen4g.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public candidate()
        {
            this.focusNewAdmin_candidate = new HashSet<focusNewAdmin_candidate>();
            this.citizen4 = new HashSet<citizen4>();
            this.msg_citizen4_candidates = new HashSet<msg_citizen4_candidates>();
        }
    
        public int idCandidates { get; set; }
        public int idCard { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public byte[] Image { get; set; }
        public string Description { get; set; }
        public string DescriptionCampaign { get; set; }
        public string LinkCampaign { get; set; }
        public byte[] LogoCampaign { get; set; }
        public Nullable<int> FocusNewAdmin { get; set; }
        public int idTown { get; set; }
        public int idUsers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<focusNewAdmin_candidate> focusNewAdmin_candidate { get; set; }
        public virtual town town { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<citizen4> citizen4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msg_citizen4_candidates> msg_citizen4_candidates { get; set; }
    }
}
