//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen4g.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class citizen4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public citizen4()
        {
            this.focus_citizen4 = new HashSet<focus_citizen4>();
            this.msg_citizen4_candidates = new HashSet<msg_citizen4_candidates>();
            this.needs_citizen4 = new HashSet<needs_citizen4>();
        }
    
        public int idCitizen4 { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Adress { get; set; }
        public string Gender { get; set; }
        public string CellPhone { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string EconomicActivity { get; set; }
        public string EducationLevel { get; set; }
        public Nullable<sbyte> HeadFamily { get; set; }
        public Nullable<sbyte> EmployeedNow { get; set; }
        public string WageLevel { get; set; }
        public string Profession { get; set; }
        public string TypeTransportUse { get; set; }
        public Nullable<sbyte> WorkEast { get; set; }
        public int idTown { get; set; }
        public int idUsers { get; set; }
        public int idCandidates { get; set; }
    
        public virtual candidate candidate { get; set; }
        public virtual town town { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<focus_citizen4> focus_citizen4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<msg_citizen4_candidates> msg_citizen4_candidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<needs_citizen4> needs_citizen4 { get; set; }
    }
}
