//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen4g.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class focusNewAdmin_candidate
    {
        public int idfocusNewAdmin_candidate { get; set; }
        public int idFocusNewAdmin { get; set; }
        public int idCandidate { get; set; }
    
        public virtual candidate candidate { get; set; }
        public virtual FocusNewAdmin FocusNewAdmin { get; set; }
    }
}
