//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen4g.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class focus_citizen4
    {
        public int idFocus_Citizen4col { get; set; }
        public int idFocus { get; set; }
        public int idCitizen4 { get; set; }
        public string DescriptionAdd { get; set; }
    
        public virtual citizen4 citizen4 { get; set; }
        public virtual focus focus { get; set; }
    }
}
