//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen4g.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class focusNewAdmin_candidate
    {
        public int idfocusNewAdmin_candidate { get; set; }
        public int idFocusNewAdmin { get; set; }
        public int idCandidate { get; set; }
    
        public virtual candidate candidate { get; set; }
        public virtual FocusNewAdmin FocusNewAdmin { get; set; }
    }
}
