//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen4g.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class focus_citizen4
    {
        public int idFocus_Citizen4col { get; set; }
        public int idFocus { get; set; }
        public int idCitizen4 { get; set; }
        public string DescriptionAdd { get; set; }
    
        public virtual citizen4 citizen4 { get; set; }
        public virtual focus focus { get; set; }
    }
}
