//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen4g.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg_citizen4_candidates
    {
        public int idMessageCitizen4 { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public byte[] Image { get; set; }
        public string Answer { get; set; }
        public int idCandidates { get; set; }
        public int idCitizen4 { get; set; }
        public int idMessageType { get; set; }
    
        public virtual candidate candidate { get; set; }
        public virtual citizen4 citizen4 { get; set; }
        public virtual messagetype messagetype { get; set; }
    }
}
