//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen4g.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg_citizen4_candidates
    {
        public int idMessageCitizen4 { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public byte[] Image { get; set; }
        public string Answer { get; set; }
        public int idCandidates { get; set; }
        public int idCitizen4 { get; set; }
        public int idMessageType { get; set; }
    
        public virtual candidate candidate { get; set; }
        public virtual citizen4 citizen4 { get; set; }
        public virtual messagetype messagetype { get; set; }
    }
}
