//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen4g.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sector
    {
        public int idSector { get; set; }
        public string NameSector { get; set; }
        public int idTown { get; set; }
    
        public virtual town town { get; set; }
    }
}
