//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citizen4g.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_profiles
    {
        public int idUsers_Profiles { get; set; }
        public int idUsers { get; set; }
        public int idProfiles { get; set; }
    
        public virtual profile profile { get; set; }
        public virtual user user { get; set; }
    }
}
